# run_scheduled_scan.py
"""
Script to run leader and specific advanced scans (MA_CROSS) for all universes
and send a combined email alert. Designed for scheduled execution.
"""
import sys
import logging
import datetime as dt
import pandas as pd

# Configure logging FIRST
log_level = logging.INFO # Or logging.DEBUG
logging.basicConfig(level=log_level, format='%(asctime)s - ScheduledScan - %(levelname)s - %(message)s', force=True)
log = logging.getLogger(__name__)

# Import leader_scan components AFTER logging is set up
try:
    # Use run_scan_for_all_universes from main for leader scan
    from leader_scan.main import run_scan_for_all_universes
    # Use run_advanced_scan_for_all from advanced_screener
    from leader_scan.advanced_screener import run_advanced_scan_for_all
    from leader_scan.alert import dispatch
    from leader_scan.config import CONFIG
except ImportError as e:
    log.critical(f"Failed import leader_scan components: {e}. Check PYTHONPATH or if script is run from parent directory.", exc_info=True)
    sys.exit(1)
except Exception as e:
    log.critical(f"Unexpected error during imports: {e}", exc_info=True)
    sys.exit(1)

# --- Configuration ---
TOP_N = 5 # Get Top 5 results per universe as requested
BENCHMARK = CONFIG.get("schedule_benchmark", "SPY")
# Use MA_CROSS type for the advanced scan filter
ADVANCED_SETUP_TYPE_FILTER = "MA_CROSS"
# Define display columns (ensure these match columns generated by your chosen scorer)
DISPLAY_COLS_LEADER = ['symbol', 'date', 'setup_type', 'score', 'r_multiple', 'Close', 'stop', 'target']
# Advanced screener might use 'entry' instead of 'Close' if defined differently in scorer
DISPLAY_COLS_ADV = ['symbol', 'date', 'setup_type', 'score', 'r_multiple', 'entry', 'stop', 'target']

def format_results_for_email(results_dict: dict, title: str, display_cols: list) -> str:
    """Formats results from a dictionary {universe: DataFrame} into a string."""
    body = f"--- {title} (Top {TOP_N}) ---\n\n"
    found_any = False
    if not results_dict or not isinstance(results_dict, dict):
        body += "No results found or results format incorrect.\n"
        return body

    sorted_universes = sorted(results_dict.keys())
    for universe in sorted_universes:
        df = results_dict.get(universe)
        # Ensure df is a non-empty pandas DataFrame
        if isinstance(df, pd.DataFrame) and not df.empty:
            found_any = True
            body += f"=== {universe.upper()} ===\n"
            temp_df = df.copy()
            # Select only columns that actually exist in the DataFrame
            final_cols_existing = [col for col in display_cols if col in temp_df.columns]

            if not final_cols_existing:
                body += "No display columns found in results DataFrame.\n\n"
                continue # Skip if no columns to display

            # Format date if present
            if 'date' in temp_df.columns:
                try:
                    # Ensure date is formatted correctly, handle potential errors
                    temp_df['date'] = pd.to_datetime(temp_df['date'], errors='coerce').dt.strftime('%Y-%m-%d')
                except Exception:
                    log.warning(f"Could not format date column for {universe} in {title}", exc_info=False)
                    pass # Keep original if formatting fails

            # Format numbers and create string representation
            try:
                body += temp_df[final_cols_existing].to_string(index=False, float_format="%.2f") + "\n\n"
            except Exception as e:
                 log.error(f"Error formatting DataFrame to string for {universe} in {title}: {e}")
                 body += f"Error displaying results for {universe}.\n\n"

        # else:
            # Optional: Report empty universes if desired
            # body += f"=== No results found for {universe.upper()} ===\n\n"

    if not found_any:
        body += f"No setups found matching criteria in any universe for {title}.\n"
    return body

def main():
    """Main execution function for scheduled scan."""
    log.info("Starting scheduled scan run...")
    # Check for essential email config from environment variables/secrets
    if not all([CONFIG.get("smtp_host"), CONFIG.get("smtp_user"), CONFIG.get("smtp_password"), CONFIG.get("from_email"), CONFIG.get("to_emails")]):
        log.error("Email configuration incomplete via ENV VARS (LS_...). Cannot send alert.")
        # Exit cleanly if config is missing in a scheduled run
        sys.exit(1)

    log.info(f"Running standard leader scan (Top {TOP_N}, Benchmark {BENCHMARK})...")
    # Call the function from main.py, ensure it returns results
    leader_results = run_scan_for_all_universes(top_per_universe=TOP_N, benchmark=BENCHMARK, return_results=True)

    log.info(f"Running advanced scan (Top {TOP_N}, Type {ADVANCED_SETUP_TYPE_FILTER}, Benchmark {BENCHMARK})...")
    # Call the function from advanced_screener.py with the specific type filter
    advanced_results = run_advanced_scan_for_all(top_per_universe=TOP_N, setup_type_filter=ADVANCED_SETUP_TYPE_FILTER, benchmark=BENCHMARK, return_results=True)

    log.info("Formatting email body...")
    today_str = dt.date.today().strftime('%Y-%m-%d')
    subject = f"Stock Scan Results - {today_str}"

    email_body = f"Scan Report for {today_str}\n"
    email_body += "="*40 + "\n\n"

    # Format Leader Scan Results
    email_body += format_results_for_email(leader_results, "Standard Leader Scan", DISPLAY_COLS_LEADER)
    email_body += "="*40 + "\n\n"

    # Format Advanced Scan (MA_CROSS) Results
    email_body += format_results_for_email(advanced_results, f"Advanced Scan ({ADVANCED_SETUP_TYPE_FILTER})", DISPLAY_COLS_ADV)
    email_body += "="*40 + "\n"

    # Send Email using dispatch function from alert.py
    log.info(f"Attempting to send combined email alert to: {CONFIG.get('to_emails')}")
    try:
        dispatch(subject, email_body)
        log.info("Combined email alert dispatched successfully.")
    except Exception as e:
        log.error(f"Failed to send combined email alert: {e}", exc_info=True)
        # Exit with error if email dispatch fails in scheduled run
        sys.exit(1)

    log.info("Scheduled scan run finished successfully.")

if __name__ == "__main__":
    main()